trigger:
- master

variables:
- name: APPSYSID
  value: d396256c1baf9410fe0165f8bc4bcb8d
- name: TESTSUITEID
  value: b1ae55eedb541410874fccd8139619fb
- name: BRANCH
  value: $(Build.SourceBranchName)

stages:
- stage: Build
  condition: ne(variables['Build.SourceBranch'], 'refs/heads/master')
  jobs:
  - job: ApplyChange_Publish
    steps: 
    - task: ServiceNow-CICD-SC-Apply@2
      inputs:
        connectedServiceName: 'chiarngdevdemo'
        appSysId: '$(APPSYSID)'
        branchName: '$(BRANCH)'
    - task: ServiceNow-CICD-App-Publish@2
      inputs:
        connectedServiceName: 'chiarngdevdemo'
        sysId: '$(APPSYSID)'
        versionFormat: 'detect'
        isAppCustomization: true

- stage: Test
  condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/master'))
  jobs:
  - job: InstallToTest_RunTest
    steps:
    - task: ServiceNow-CICD-App-Install@2
      inputs:
        connectedServiceName: 'chiarngtestdemo'
        sysId: '$(APPSYSID)'
        autoUpgradeBaseApp: true
        baseAppVersion: '<ver>'
    - task: ServiceNow-CICD-TestSuite-Run@2
      inputs:
        connectedServiceName: 'chiarngtestdemo'
        testSuiteSysId: '$(TESTSUITEID)'
        browserName: 'any'
  - job: Rollback
    dependsOn: InstallToTest_RunTest
    condition: failed()
    steps:
    - task: ServiceNow-CICD-App-Rollback@2
      inputs:
        connectedServiceName: 'chiarngtestdemo'
        sysId: '$(APPSYSID)'
        autodetectVersion: 'yes'

- stage: DeployToProd
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  jobs:
  - job: InstallToProd
    steps:
    - task: ServiceNow-CICD-App-Install@2
      inputs:
        connectedServiceName: 'chiarngproddemo'
        sysId: '$(APPSYSID)'
