# This is example workflow for Instance Scan feature, new to the Quebec release.
# Several types of scans can be run, for more details please see the Instance Scan API documentation in https://developer.servicenow.com/dev.do#!/reference/api/quebec/rest/cicd-api
# Please fill <gaps> with proper values.

trigger:
  - master

stages:
  - stage: Test
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
    jobs:
      - job: Scan_Instance
        steps:
          - checkout: self
          - task: ServiceNow-CICD-Scan-Instance@2
            displayName: ServiceNow CI/CD Scan Instance
            inputs:
              connectedServiceName: '<client_host>'
              scanType:        'full'     # required(full|point|suiteCombo|suiteScoped|suiteUpdate)
              targetTable:     '<table>'  # required if type=point
              targetSysId:     '<sys_id>' # required if type=point
              comboSysId:      '<sys_id>' # required if type=suiteCombo
              suiteSysId:      '<sys_id>' # required if type=suiteScoped|suiteUpdate
              appScopeSysIds:  '<id,id>'  # required if type=suiteScoped
              updateSetSysIds: '<id,id>'  #required if type=suiteUpdate
